version: 2
jobs:
  build:
    working_directory: /go/src/github.com/hellomd/go-microservice-starter
    docker:
      - image: ribeirofelix/go-docker-compose
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - setup_remote_docker
      - run: mkdir -p "$TEST_RESULTS"
      - run:
          name: Run unit tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make test | tee ${TEST_RESULTS}/go-test.out
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results
